name: Smartwatch Image Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions: 
  contents: read
  packages: write
  
jobs:
  build-smartwatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Docker meta
        id: meta_smartwatch
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/themicknugget/smartwatch
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{branch}}-{{date 'YYYYMMDD'}}
            type=raw,value={{branch}}-latest

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_smartwatch.outputs.tags }}
          labels: ${{ steps.meta_smartwatch.outputs.labels }}
